config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :games
  devise_for :users

  root 'welcome#index'
  get '/collection' => 'collections#index'
  resources :users, only: [:show, :index]
  resources :search, only: :index

end

app/models/game.rb
class Game < ActiveRecord::Base

  belongs_to :user
  has_many :reviews


end

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :user
  belongs_to :game

 

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :games
has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

    def after_sign_out_path_for(resource_or_scope)
    root_path
  end

end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController

def index 
  @collection = current_user.games
end


#def Product.out_of_stock
 # Rails.cache.fetch("out_of_stock_products", :expires_in => 5.minutes) do
  #  Product.all.joins(:inventory).conditions.where("inventory.quantity = 0")
  #end
#end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.where(id: params[:id]).first
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)
    @game.user_id = current_user.id 
    @game.img_url_small = APIS::Giantbomb.new.game_by_id(@game.game_id)["results"]["image"]["screen_url"]
    @game.img_url_large = APIS::Giantbomb.new.game_by_id(@game.game_id)["results"]["image"]["small_url"]
    @game.deck = APIS::Giantbomb.new.game_by_id(@game.game_id)["results"]["deck"]
    @game.developers = APIS::Giantbomb.new.game_by_id(@game.game_id)["results"]["developers"][0]["name"]
    @game.genre = APIS::Giantbomb.new.game_by_id(@game.game_id)["results"]["genres"][0]["name"]

    respond_to do |format|
      if @game.save
        format.html { redirect_to search_index_path, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def avg_user_score
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:user_id, :game_id, :game_name, :platforms, :img_url_small, :img_url_large, :deck, :developers, :genre)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.paginate(:page => params[:page],:per_page => 5)
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @reviews = Review.last(9).reverse
    @review = Review.where(id: params[:id]).first
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    respond_to do |format|
      if @review.save
        format.html { redirect_to collection_path, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:title, :body, :rating, :game_id)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  skip_before_action :verify_authenticity_token

  def index
    @search = APIS::Giantbomb.new.game_search(params[:search_input])["results"]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def index
  @users = User.all
end

def show
  @user = User.where(id: params[:id]).first
  @collection = @user.games
end



end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

def index
  @reviews = Review.last(9).reverse
  @games = Game.all
end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/collections/index.html.erb
<% javascript_include_tag 'collection.js' %>
<% stylesheet_link_tag 'collection.css' %>
<% image_path('loading-sping.svg') %>
<div id="user_info">
<h1>Your Collection </h1>

<p> games owned: <%= current_user.games.count %> </p>
</div>
<div  id="collection_container"class="container-fluid">
<ul class="gridder">
	 <% @collection.each do |a| %>
        <% @api_hit = APIS::Giantbomb.new.game_by_id(a.game_id)["results"] %>
	     <li class="gridder-list" data-griddercontent="#<%= a.game_id %>">
        <img src="<%= a.img_url_small%>" />
    	</li>
    	<div  id="<%= a.game_id%>" class="gridder-content">
  
            <div class="container-fluid">
                <div class="row">
                    <div class="col-xs-6"> 
    		              <img class="big_img" src="<%= a.img_url_small %>">
                    </div>
               
            <div id="game_details" class="col-xs-6"> 
               <h2 id="collection_game_name"> <%= a.game_name %> </h2>
               <p> <%= @api_hit["deck"] %> </p>
               <p><strong> Developed By:</strong> <%= @api_hit["developers"][0]["name"] unless @api_hit["developers"].nil? %></p>
               <p><strong> Genre: </strong><%= @api_hit["genres"][0]["name"] unless @api_hit["genres"].nil? %></p>
                   <div class="container-fluid">
                        <div class="row">
                            <div id="score_review_button_wrapper" class="col-xs-12">
                                <% if a.reviews.first.nil? %>
                              <form method="GET" action="/games/<%=a.id%>">
                              <button type="submit"class="btn btn-primary">Rate/Review</button>
                                </form>
                                <% else %>
                                <div id="score_display">
                                    <div id="stars-existing" class="starrr" data-rating='<%= a.reviews.first.rating%>'> Your Score: </div>         
                                    <div class="review_link">
                                    <a  href="/reviews/<%= a.reviews.first.id %>"> Read your review </a>
                                  </div>
                                </div>
                                <%end%>
                            </div>
                        </div>
              
                    </div>
            
            </div> 
             </div>
            </div>

    	</div>
	  <%end%>
</ul>
</div>

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :id %><br>
    <%= f.text_field :id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Games</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.user_id %></td>
        <td><%= game.id %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<div id="review_container" class="container-fluid">
<div class="container-fluid">
    <div class="row">
        <div class="col-md-7">
            <div class="well well-sm">
                <form action="/reviews" method="POST">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="name">
                                Title</label>
                            <input name="review[title]" type="text" class="form-control" id="title" placeholder="Enter name" required="required" />
                        </div>
                    </div>

                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="name">
                                Your Review</label>
                            <textarea name="review[body]" id="body" class="form-control" rows="9" cols="25" required="required"
                                placeholder="Your Review"></textarea>
                        </div>
                    </div>
                    <div class="col-xs-12">
			          <div id="star_box"class="row lead">
			        	<div id="stars" class="starrr"></div>
			        	You gave a rating of <span id="count">0</span> star(s)
						</div>
                        <input type="hidden" name="review[rating]" value="" id="star_output">
                        <input type="hidden" name="review[game_id]" value="<%= @game.id %>" id="game_id">
					</div>
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-primary pull-right" id="btnContactUs">
                            Submit</button>
                    </div>
                </div>
                </form>
            </div>
        </div>
        <div id="review_side" class="col-md-5">
        		<h1><span id="review_side_small"> You're reviewing</span> <%= @game.game_name %></h1>
                <img src="<%= @game.img_url_small %>">
        	</div>
    </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gamebase</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/masonry/3.3.2/masonry.pkgd.js"></script>
	<% javascript_include_tag 'imagesloaded.pkgd.js' %>
	<% javascript_include_tag 'gridder.js' %>
	<% javascript_include_tag 'lightbox.js' %>
	<% javascript_include_tag 'welcome.js' %>
	<% javascript_include_tag 'masonry.pkgd.js' %>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/3.1.8/imagesloaded.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha256-Sk3nkD6mLTMOF0EOpNtsIry+s1CsaqQC1rVLTAy+0yc= sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
	<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro|Raleway|Roboto+Slab|Poiret+One|Cabin' rel='stylesheet' type='text/css'>
	<link href='https://fonts.googleapis.com/css?family=Muli' rel='stylesheet' type='text/css'>
</head>
<body>
	<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div id="header_content">
			<span id="home_link"> <a href="/">GameBase</a></span>

			<span id="nav">
				<ul>
					<li><%= link_to "Sign-in", new_user_session_path unless !current_user.nil?%></li>
					<li><%= link_to "Sign-up", new_user_registration_path unless !current_user.nil? %></li>
					<li> <%= link_to "Reviews", reviews_path %></li>
					<li id="collection_button"><%= link_to "Your Collecton", collection_path unless current_user.nil? %></li>
					<li><%= link_to "Sign-Out", destroy_user_session_path, :method => :delete unless current_user.nil?%></li>
				</ul>
			</span>
				<form id="game_search" class="form-inline" method="GET" action="/search">
				  <div class="form-group">
				    <label for="exampleInputName2"></label>
				    <input type="text" class="form-control" id="exampleInputName2" placeholder="Search for a game" name="search_input">
				  </div>
				  <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
				</form>
			</div>
  </div>
</nav>
<!-- // Navigation Bar -->

	<!--<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>-->



<%= yield %>
<footer>
	<div id="footer" class="row">
		<div class="col-xs-12">
			<p> Site by: <a href="https://www.linkedin.com/pub/patrick-keenan/103/59b/13"> Patrick Keenan </a></p>
			<p><a href="https://github.com/Taccyp"> My GitHub</a></p>
		</div>
	</div>
</footer>
</body>
</html>

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<% if  @reviews.count == 0 %>
<h1 id="no_reviews"> Looks like no one has written any reviews yet.</h1>
<%else%>

<div id="review_wrapper" class="container">
  <% @reviews.each do |a| %>
  <div id="reviews_box_index" class="row">
    <div id="review_header" class="col-xs-12">
      <div class="game_user_header">
        <h1> <%= a.game.game_name unless a.game.game_name.nil? %></h1>
        <h3> A review by: <a href="/users/<%= a.user.id %>"><%= a.user.email unless a.user.email.nil? %></a> </h3>
      </div>
      <div class="review_title_header">
        <p id="review_title"> <%= a.title unless a.title.nil? %> </p>
      </div>
      <div class="review_stars_header">
        <div id="stars-existing" class="starrr" data-rating='<%= a.rating%>'>
        </div>
      </div>
      <p> <%= a.created_at.strftime("%Y-%m-%d") %> </p>
      <span id="full_review_link"> <a href="/reviews/<%= a.id%>">Read the full review </span></a>
    
    </div>
  </div>
  <%end%>
</div>
<div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @reviews %>
    </div>
    <%= will_paginate @reviews, :container => false %>
  </div>

  <%end%>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<div id="review_wrapper" class="container">
	<div class="row">
		<div id="review_header" class="col-xs-12">
			<div class="game_user_header">
				<h1> <%= @review.game.game_name %></h1>
				<h3> A review by: <a href="/users/<%= @review.user.id %>"><%= @review.user.email %></a> </h3>
			</div>
			<div class="review_title_header">
				<p id="review_title"> <%= @review.title %> </p>
			</div>
			<div class="review_stars_header">
				<div id="stars-existing" class="starrr" data-rating='<%= @review.rating%>'>
				</div>
			</div>
			<div id="review_body">
				<p> <%= @review.body %>  </p>
			</div>
		
		</div>
			<div id="review_image" class="col-xs-12">
				<% if @reviews.count  <= 0 %>
<h1> no reviews... </h1>
<%else%>
<div class="container">
	<div class="row">
		<h2>Latest Reviews</h2>
	</div>
</div>
<div class="carousel-reviews broun-block">
    <div class="container">
        <div class="row">
            <div id="carousel-reviews" class="carousel slide" data-ride="carousel">
            
                <div class="carousel-inner">
                    <div class="item active">
                	    <div class="col-md-4 col-sm-6">
        				    <div class="block-text rel zmin">
        				    	<h2><%= @reviews[0].game.game_name%></h2>
						        <a title="" href="/reviews/<%= @reviews[0].id %>"><%= @reviews[0].title %></a>
						        <div id="score_display">
							   <div id="stars-existing" class="starrr" data-rating='<%= @reviews[0].rating %>'>Score: </div>
								</div>
						        <p><%= @reviews[0].body %></p>
							    <ins class="ab zmin sprite sprite-i-triangle block"></ins>
					        </div>
							<div class="person-text rel">
								<a title="" href="#"><%= @reviews[0].user.email %></a>
							</div>
						</div>
            			<div class="col-md-4 col-sm-6">
        				    <div class="block-text rel zmin">
        				    	<h2><%= @reviews[1].game.game_name%></h2>
						        <a title="" href="/reviews/<%= @reviews[1].id %>"><%= @reviews[1].title %></a>
							   <div id="stars-existing" class="starrr" data-rating='<%= @reviews[1].rating%>'> Score: </div>
						        <p><%= @reviews[1].body %></p>
							    <ins class="ab zmin sprite sprite-i-triangle block"></ins>
					        </div>
							<div class="person-text rel">
								<a title="" href="#"><%= @reviews[1].user.email %></a>
							</div>
						</div>
					<div class="col-md-4 col-sm-6">
        				    <div class="block-text rel zmin">
        				    	<h2><%= @reviews[2].game.game_name%></h2>
						        <a title="" href="/reviews/<%= @reviews[2].id %>"><%= @reviews[2].title %></a>
							   <div id="stars-existing" class="starrr" data-rating='<%= @reviews[2].rating%>'> Score: </div>
						        <p><%= @reviews[2].body %></p>
							    <ins class="ab zmin sprite sprite-i-triangle block"></ins>
					        </div>
							<div class="person-text rel">
								<a title="" href="#"><%= @reviews[2].user.email %></a>
							</div>
						</div>
                    </div>
                    <div class="item">
                       <div class="col-md-4 col-sm-6">
        				    <div class="block-text rel zmin">
        				    	<h2><%= @reviews[3].game.game_name%></h2>
						        <a title="" href="/reviews/<%= @reviews[3].id %>"><%= @reviews[3].title %></a>
							  <div id="stars-existing" class="starrr" data-rating='<%= @reviews[3].rating %>'>Score: </div>    
						        <p><%= @reviews[3].body %></p>
							    <ins class="ab zmin sprite sprite-i-triangle block"></ins>
					        </div>
							<div class="person-text rel">
								<a title="" href="#"><%= @reviews[3].user.email %></a>
							</div>
						</div>
            			<div class="col-md-4 col-sm-6">
        				    <div class="block-text rel zmin">
        				    	<h2><%= @reviews[4].game.game_name%></h2>
						        <a title="" href="/reviews/<%= @reviews[4].id %>"><%= @reviews[4].title %></a>
							   <div id="stars-existing" class="starrr" data-rating='<%= @reviews[4].rating%>'> Score: </div>
						        <p><%= @reviews[4].body %></p>
							    <ins class="ab zmin sprite sprite-i-triangle block"></ins>
					        </div>
							<div class="person-text rel">
								<a title="" href="#"><%= @reviews[4].user.email %></a>
							</div>
						</div>
					<div class="col-md-4 col-sm-6">
        				    <div class="block-text rel zmin">
        				    	<h2><%= @reviews[5].game.game_name%></h2>
						        <a title="" href="/reviews/<%= @reviews[5].id %>"><%= @reviews[5].title %></a>
							   <div id="stars-existing" class="starrr" data-rating='<%= @reviews[5].rating%>'> Score: </div>
						        <p><%= @reviews[5].body %></p>
							    <ins class="ab zmin sprite sprite-i-triangle block"></ins>
					        </div>
							<div class="person-text rel">
								<a title="" href="#"><%= @reviews[5].user.email %></a>
							</div>
						</div>
                    </div>
                    <div class="item">
                      <div class="col-md-4 col-sm-6">
        				    <div class="block-text rel zmin">
        				    	<h2><%= @reviews[6].game.game_name%></h2>
						        <a title="" href="/reviews/<%= @reviews[6].id %>"><%= @reviews[6].title %></a>
							   <div id="stars-existing" class="starrr" data-rating='<%= @reviews[6].rating%>'> Score: </div>
						        <p><%= @reviews[6].body %></p>
							    <ins class="ab zmin sprite sprite-i-triangle block"></ins>
					        </div>
							<div class="person-text rel">
								<a title="" href="#"><%= @reviews[6].user.email %></a>
							</div>
						</div>
            			<div class="col-md-4 col-sm-6">
        				    <div class="block-text rel zmin">
        				    	<h2><%= @reviews[7].game.game_name%></h2>
						        <a title="" href="/reviews/<%= @reviews[7].id %>"><%= @reviews[7].title %></a>
							   <div id="stars-existing" class="starrr" data-rating='<%= @reviews[7].rating%>'> Score: </div>
						        <p><%= @reviews[7].body %></p>
							    <ins class="ab zmin sprite sprite-i-triangle block"></ins>
					        </div>
							<div class="person-text rel">
								<a title="" href="#"><%= @reviews[7].user.email %></a>
							</div>
						</div>
						<div class="col-md-4 col-sm-6">
        				    <div class="block-text rel zmin">
        				    	<h2><%= @reviews[8].game.game_name%></h2>
						        <a title="" href="/reviews/<%= @reviews[8].id %>"><%= @reviews[8].title %></a>
							   <div id="stars-existing" class="starrr" data-rating='<%= @reviews[8].rating%>'> Score: </div>
						        <p><%= @reviews[8].body %></p>
							    <ins class="ab zmin sprite sprite-i-triangle block"></ins>
					        </div>
							<div class="person-text rel">
								<a title="" href="#"><%= @reviews[8].user.email %></a>
							</div>
						</div>
                    </div>                    
                </div>
                <a class="left carousel-control" href="#carousel-reviews" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#carousel-reviews" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
            </div>
        </div>
    </div>
</div>
</div>




<%end%>
			</div>
		</div>
	</div>


<%= link_to 'Edit', edit_review_path(@review) %>

app/views/search/index.html.erb
<% javascript_include_tag 'search' %>
<p> hello <%= current_user.email unless current_user.nil? %> </p>
<% if @search == [] %>
<h1 id="no_search_results"> Looks like nothing in the database matched your search ... :( </h1>
<%end%>
<div id="search_results_container"class="container">
<div>
	<% @search.each do |result| %>
	<div class="search_result">
	<h2> <%= result["name"] %> </h2>
	<img src='<%= result["image"]["icon_url"] unless result["image"].nil? %>' >
	<% if !result["original_release_date"].nil? %>
	<p id="release_year">Released: <%=Date.parse(result["original_release_date"]).year %></p>
	<%end%>
	<p id="game_deck"> <%= result["deck"] %> </p>
		<% if !result["platforms"].nil? %>
	 		<span id="platform_list"> Platforms:<% result["platforms"].each do |platform| %>
	 			<%= platform["name"] %> 
	 		</span>
	 	<%end%>

	 <%end%>
	<% if  !current_user.nil? and Game.where(user_id: current_user.id).exists?(:game_id => result["id"]) %>
	<p id="in_collection_notice"> In your collection </p>
	
	<%else%>
		<%= form_for Game.new, remote: true do |f| %>
		<%= f.hidden_field :game_id, :value => result["id"] %>
		<%= f.hidden_field :game_name, :value => result["name"] %>
		<%= f.hidden_field :platforms, :value => result["platforms"] %>
		<%= f.hidden_field :img_url, :value => result["image"]["icon_url"] unless result["image"].nil?  %>
		<%= submit_tag "Add to Collection", :class => 'btn btn-success', :id=> result["id"] %>
			<%end%>
			</div>
		<%end%>
	<%end%>
	
	</div>
</div>

app/views/users/index.html.erb
<div class="grid">
	<% @users.each do |a| %>
	
  <!-- width of .grid-sizer used for columnWidth -->
  <div class="grid-sizer"></div>
  <div class="grid-item">
  	<h2> <%= a.email %></h2>
  	<h2> Games Owned <%= a.games.count %> </h2>
  	<h2> <a href="/users/<%= a.id %>">Their Collection </a>
  </div>
  <div class="grid-item grid-item--width2"></div>

	<%end%>
</div>

app/views/welcome/search.html.erb
<% @search.each do |result| %>
<img src='<%= result["image"]["icon_url"] unless result["image"].nil? %>' >
<p> <%= result["name"] %> </p>
<p> <%= result["deck"] %> </p>
<%end%>